services:
  backend:
    image: registry.gitlab.propulsion-home.ch/full-stack/batch-31-feb-2025/final-project-ticket/ticket:latest
    ports:
      - "8000:8000"
    command: "sh /scripts/dev.sh"
    env_file:
      - ./envs/dev.env
    volumes:
      - ./backend:/backend
    depends_on:
      - postgres

  postgres:
    image: postgres:latest
    ports:
      - "5432:5432"
    env_file:
      - ./envs/dev.env
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
