# Generated by Django 5.1.7 on 2025-04-14 14:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ticket',
            old_name='user',
            new_name='user_profile',
        ),
    ]
