# Generated by Django 5.1.7 on 2025-04-15 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0003_alter_ticket_date_alter_ticket_location_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
