# Generated by Django 5.1.7 on 2025-04-16 11:28

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0004_alter_ticket_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='location',
            field=models.CharField(default='Unknown Location', max_length=255),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='title_artist',
            field=models.CharField(default='Unnamed Event', max_length=255),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='venue',
            field=models.CharField(default='Unknown Venue', max_length=255),
        ),
    ]
