# Generated by Django 5.1.7 on 2025-04-29 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0006_ticket_created_at_ticket_last_updated'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='category',
            field=models.CharField(default='Unnamed Category', max_length=20),
        ),
    ]
