# Generated by Django 5.1.7 on 2025-04-29 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0007_ticket_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='latitude',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='ticket',
            name='longitude',
            field=models.FloatField(default=0.0),
        ),
    ]
