# Generated by Django 5.1.7 on 2025-04-29 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserProfile', '0003_useraccount_created_at_useraccount_last_updated'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccount',
            name='location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
